package common

const (
	SQL_InitVariables    = "SELECT Name, Value from Variable"
	SQL_InitCityMap      = "SELECT ID,Name from City"
	SQL_InitCommunityMap = "SELECT ID,City,Latitude,Longitude,Name,Address from Community"
	SQL_InitHKPs_C       = "SELECT UserID,Community FROM RoleHKP"
	SQL_InitHKPs_U       = "SELECT ID,NickName,LastName,FirstName,Cellphone,IDCardType,IDCardNum,Sex,Birthday,Birthplace,RegTime,Mail,Inviter,HealthCardTimeout FROM User where ID in (%s)"
	SQL_InitHKPs_J       = "SELECT UserID,BeginTime,JobID,Price,Description,Version FROM HKPJobs"
	SQL_InitHKPs_R       = "SELECT UserID,Job,Times,TotalSpeed,TotalQuality,TotalAttitude,RejectTimes,FailTimes FROM HKPRanking"
	SQL_GetRecommend     = "SELECT Pic,Op,Value from Recommend"

	SQL_SetVerifyCode       = "INSERT INTO VerifyCode VALUES(?,?,?,?) on duplicate key update Code=?, Timeout=?"
	SQL_VerifyCode          = "select Timeout from VerifyCode where Cellphone = ? && ForWhat = ? && Code = ?"
	SQL_GetPassword         = "select Password from AppClient where UserID = ? && DeviceID = ?"
	SQL_GetUid              = "select ID from User where Cellphone = ?"
	SQL_GetUserByPhone      = "select ID,NickName from User where Cellphone = ?" //未完成，只取了ID和昵称
	SQL_UpdateUserInfo      = "UPDATE User SET %s where ID = ?"
	SQL_CreateUser          = "INSERT INTO User(NickName, LastName, FirstName, Cellphone, IDCardType, IDCardNum, Sex, Birthday, Birthplace, Mail, Inviter,HealthCardTimeout) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)"
	SQL_CreateAccount       = "INSERT INTO Account(UserID, Balance, Score, Coupons)VALUES(?,?,?,?)"
	SQL_UpdateUserCellphone = "update User set cellphone=? where ID=?"
	SQL_AddCoupons          = "update Account set Coupons=Coupons+? where UserID=?"
	SQL_CreateAppClient     = "INSERT INTO AppClient(UserID, Password, DeviceName, DeviceId, Platform,LastUpdate)VALUES(?,?,?,?,?,?)"
	SQL_NewPassword         = "INSERT INTO AppClient(UserID, Password, DeviceName, DeviceId, Platform,LastUpdate)VALUES(?,?,?,?,?,?)on duplicate key update DeviceName=?,Password=?,Platform=?,LastUpdate=?"
	SQL_CreateAddress       = "INSERT INTO Address(UserID, Community, Address, Status,LastUse)VALUES(?,?,?,?,?)"
	SQL_IsValidCommunity    = "SELECT ID FROM Community WHERE ID=?"
	SQL_UpdateInviter       = "update User set Inviter=? where ID=?"
	//	SQL_UpdateDefaultAddr   = "update User set DefaultAddr=? where ID=?"
	//	SQL_IsDefaultAddr       = "SELECT DefaultAddr from User where ID=?"
	SQL_DelAddress          = "UPDATE Address set Status=0 where UserID=? and AddrID=?"
	SQL_ListAddress         = "SELECT AddrID,Community,Address from Address where UserID=? and Status=1 order by LastUse desc"
	SQL_UpdateAddress       = "UPDATE Address set %s where UserID=? and AddrID=?"
	SQL_AddCollection       = "INSERT INTO Collection(Customer, ServiceProvider, Role, Job,CollectTime)VALUES(?,?,?,?,?)"
	SQL_DelCollection       = "DELETE FROM Collection WHERE %s"
	SQL_ListCollection      = "SELECT ServiceProvider from Collection where %s limit ?,?"
	SQL_ListHistory         = "SELECT ServiceProvider,LastTime from History where %s limit ?,?"
	SQL_GetHKPJobMaxVersion = "SELECT BeginTime,Price,Description,Version from HKPJobs where UserID=? and JobID=? order by Version desc limit 1"
	SQL_GetBalance          = "SELECT Balance,Score,Coupons from Account where UserID=?"
	SQL_Feedback            = "INSERT INTO Feedback(UserID,Content)VALUES(?,?)"
	SQL_Vote                = "UPDATE Vote SET Count=Count+1 WHERE ID in(%v)"
	SQL_ListOptions         = "SELECT ID,Name,Pic,Detail FROM Vote"

	SQL_GetCSR         = "SELECT ID FROM CSR"
	SQL_GetUserAddress = "SELECT Community,Address from Address where UserID=? and AddrID=?"
	//由于mysql的缺陷in条件只能拼字符串
	SQL_GetHKPsNoTime_FindOrders = "SELECT ID,Phase from `Order` where Role=? and Community in (%s) and Phase < ? and ServiceStart >= ? and ServiceStart < ?"
	SQL_GetHKPsNoTime_FindHKPs   = "SELECT UserID,Confirm,OrderID from HKPOrderProvider where OrderID in (%s)"
	SQL_AddOrder                 = "INSERT INTO `Order`(Role,Job,Customer,Address,Community,Persons,StartTime,Phase,PhaseTime,PhaseReason,CSR,ServiceStart,Duration,Description)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)"
	SQL_AddHKPOrderProvider      = "INSERT INTO HKPOrderProvider(OrderID,UserID,JobVersion,Recommend,AvailableTime,Confirm,Priority,Speed,Quality,Attitude)VALUES(?,?,?,?,?,?,?,?,?,?)"
	SQL_AddHKPFailTimes          = "UPDATE HKPRanking set FailTimes=FailTimes+? where UserID=? and Job=?"
	SQL_GetOrder                 = "SELECT Role,Job,Customer,Address,Community,Persons,StartTime,Phase,PhaseTime,PhaseReason,CSR,ServiceStart,Duration,Description from `Order` where ID = ?"
	SQL_GetHKPJob                = "SELECT BeginTime,Price,Description from HKPJobs where UserID=? and JobID=? and Version=?"
	SQL_ListOrder                = "SELECT ID,Role,Job,Customer,Address,Community,Persons,StartTime,Phase,PhaseTime,PhaseReason,CSR,ServiceStart,Duration,Description from `Order` where %s"
	SQL_UpdateOrder              = "UPDATE `Order` set Role=?,Job=?,Customer=?,Address=?,Community=?,Persons=?,StartTime=?,Phase=?,PhaseTime=?,PhaseReason=?,CSR=?,ServiceStart=?,Duration=?,Description=? where ID=?"
	SQL_GetConfirmedHKPProviders = "SELECT h.UserID,JobVersion,Recommend,AvailableTime,Priority,Speed,Quality,Attitude,j.BeginTime,j.Price,j.Description from HKPOrderProvider h,HKPJobs j where OrderID=? and j.UserID = h.UserID and j.JobID=? and j.Version=h.JobVersion and Confirm=?"
	SQL_GetHKPProviders          = "SELECT h.UserID,JobVersion,Recommend,AvailableTime,Confirm,Priority,Speed,Quality,Attitude,Comment,j.BeginTime,j.Price,j.Description from HKPOrderProvider h,HKPJobs j where OrderID=? and j.UserID = h.UserID and j.JobID=? and j.Version=h.JobVersion"
	SQL_UpdateHKPOrderProvider   = "UPDATE HKPOrderProvider SET JobVersion=?,Recommend=?,AvailableTime=?,Confirm=?,Priority=?,Speed=?,Quality=?,Attitude=?,Comment=? where OrderID=? and UserID=?"
	SQL_UpdateHKPRank            = "UPDATE HKPRanking SET Times=?,TotalSpeed=?,TotalQuality=?,TotalAttitude=?,RejectTimes=?,FailTimes=? where UserID=? and Job=?"
	SQL_AddHKPRankTimes          = "UPDATE HKPRanking SET Times=Times+1 where UserID=? and Job=?"
	SQL_UpdateAddressLastUse     = "UPDATE Address SET LastUse=? WHERE AddrID=?"
	SQL_GetHKPRanks              = "SELECT UserID,Times,TotalSpeed,TotalQuality,TotalAttitude,RejectTimes,FailTimes FROM HKPRanking where UserID in (%s) and Job=%d"
	SQL_AddHistory               = "INSERT INTO History(Customer,ServiceProvider,Role,Job,LastTime)VALUES(?,?,?,?,?)on duplicate key update LastTime=?"
	SQL_HKPComments              = "SELECT o.Customer,Speed,Quality,Attitude,Comment from HKPOrderProvider h,`Order` o where o.ID=h.OrderID and h.UserID=? and Speed>0 and o.Role=2 and Comment<>\"\" order by StartTime desc limit ?,?"
	SQL_GetBSC                   = "SELECT Balance,Coupons,Score from Account where UserID=?"
	SQL_AddTransaction           = "INSERT INTO Transaction(Type,Time,OrderID,UserID,AddScore,AddCoupons,AddCash,`Desc`,Balance,Score,Coupons)VALUES(?,?,?,?,?,?,?,?,?,?,?)"
	SQL_UpdateAccount            = "UPDATE Account SET Balance=?, Score=?, Coupons=? WHERE UserID=?"
	SQL_IsFirstOrder             = "SELECT ID FROM `Order` WHERE Customer=? and Phase=?"
	SQL_ListTransactions         = "SELECT ID,Type,Time,OrderID,AddScore,AddCash,AddCoupons,Score,Balance,Coupons,`Desc` FROM `Transaction` WHERE UserID=? order by Time desc limit ?,?"
	SQL_ListGoods                = "SELECT ID,Name,Pic,Price,Detail FROM `Goods` limit ?,?"
	SQL_GetGoods                 = "SELECT ID,Name,Pic,Price,Detail,`Explain` FROM `Goods` WHERE ID=?"
	SQL_GetNeedNotifyOrders      = "SELECT ID,Customer,ServiceStart,Duration from `Order` where ServiceStart > ? and ServiceStart < ? and Phase=?"

	SQL_ListNotifications = "SELECT distinct Notification.ID,Title,Pic,Content,Url,Time FROM `Notification`,NotiLocation WHERE Province in (%v) and City in (%v) and Community in (%v) and Notification.ID=NotiLocation.NID order by Time desc limit ?,?"
	SQL_GetNotification   = "SELECT Title,Pic,Content,Url,Time FROM Notification WHERE ID=?"
)
